spring:
  application:
    name: eeit195_01_back

  # profiles:
  #   active: "@xxxx@"

  # 資料庫連線設定
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=hotel;trustServerCertificate=true
    username: sa
    password: P@ssw0rd

  # Hibernate/JPA的相關設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      # naming:
        # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        # physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #     # naming:
  #       # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  #       # physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #   open-in-view: false #如果你希望避免在視圖渲染期間執行 JPA 查詢，可以禁用 open-in-view，這樣 Spring 在處理請求時將不會持續開放 JPA 的 EntityManager
  # #conosle顏色
  # console顏色
  output:
    ansi:
      enabled: always

  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: Asia/Taipei

  mail:
    host: smtp.gmail.com # 郵件伺服器地址
    port: 587 # 郵件伺服器端口（通常是 587 用於 STARTTLS）
    username: edwin821117@gmail.com # 從環境變數讀取郵件帳號
    password: nnhw tjin gcky dhez # 從環境變數讀取郵件密碼
    properties:
      mail:
        smtp:
          auth: true # 啟用 SMTP 認證
          starttls:
            enable: true # 啟用 STARTTLS 協議
    default-encoding: UTF-8 # 設定編碼為 UTF-8

  web:
    resources:
      static-locations: file:uploads/ #弄上傳頭像的

  # 啟用定時任務
  task:
    scheduling:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    tw.com.ispan.eeit195_01_back: DEBUG

redis:
  config:
    url: localhost
line:
  client:
    id: 2006867912
    secret: 14ac6f34981e49efb2d7c3fe9186b959
  redirect:
    uri: http://localhost:8080/api/line-login/callback
  token:
    url: https://api.line.me/oauth2/v2.1/token
  profile:
    url: https://api.line.me/v2/profile
  messaging:
    channel-id: 2007172966
    channelSecret: 421d7c57e16b836a02d9715dc4e9f037
    channel-token: iT0bJvFg2UUfWNt9LdfDD7TVuyV2Kr/w/PJXS6MjuHZys7ZS5aSPJhChflTql9X3lB5b8y7zvrXYaV1qfmGsrEDzYjniUj7i0d6SyoIFLD3E4qU52xGtzTji50bf0gaoSkdWMqey675cv5bjguxUjgdB04t89/1O/w1cDnyilFU=
    webhook-url: https://46e4-114-45-197-195.ngrok-free.app
# server: 
#   servlet: 
#     context-path: /api
#   port: 8443
#   ssl: 
#     enabled: true
#     key-alias: eeitSecurity
#     key-store: classpath:server.p12
#     key-store-type: PKCS12
#     key-password: Do!ng123
#     key-store-password: Do!ng123
 
# jwt:
#   token:
#     expire: 10