spring:
  messages:
    encoding: UTF-8
  main:
    web-application-type: servlet
  application:
    name: labboot-ajax

  profiles:
    active: '@profile@'

  #資料庫連線設定
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=hotel;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8
    username: sa
    password: P@ssw0rd

  #Hibernate/JPA的相關設定
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  #conosle顏色
  output:
    ansi:
      enabled: always

  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: Asia/Taipei

jwt:
  token:
    expire: 10
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
